

export const ERR_DISPATCH='ERR_DISPATCH';
export const SET_USER_DISPATCH='USER_DISPATCH';
export const GET_BLOGGER_DISPATCH='GET_BLOGGER_DISPATCH';
export const LOAD_BLOGGER_DISPATCH='LOAD_BLOGGER_DISPATCH';
export const NO_BLOGGER_DISPATCH='NO_BLOGGER_DISPATCH';
export const CLEAR_BLOGGER_DISPATCH='CLEAR_BLOGGER_DISPATCH';


export const GET_BLOGGERS_DISPATCH='GET_BLOGGERS_DISPATCH';